language: android
jdk:
  - openjdk7
  - oraclejdk8
env:
  - TEST=java
  - TEST=android
matrix:
  exclude:
    - jdk: oraclejdk8
      env: TEST=android
android:
  components:
    - android-15
    - build-tools-21.1.1
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-15
script:
  - 'if [[ $TEST = java ]]; then mvn test -Dsurefire.useFile=false; fi'
  - 'if [[ $TEST = android ]]; then mvn install -DskipTests && cd commonmark-android-test && travis_retry ./.travis.sh; fi'
